services:
  caddy:
    image: caddy:2
    container_name: telegram-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: